'use strict';

/**
 * JSONDOConverter — bidirectional JSON ↔ DB field mapper.
 *
 * Extends EntityTransformer. Used by PreDefaultEntityHandler for all CRUD operations.
 *
 * ── Input side: transformJSONToEntity(request) ───────────────────────────────
 *   Converts the client's JSON payload into a plain column-keyed object for DB write.
 *
 *   Ref entity fields (entity set, standaloneCRUD=false):
 *     Client sends:  {"status": {"id": 301}}
 *     DB column gets: STATUSID = 301
 *     → Extract .id from nested object; write only the FK column value.
 *
 *   Sub-entity fields (standaloneCRUD=true) are SKIPPED entirely.
 *   Internal FK fields (isInternal=true) are SKIPPED — injected by handler via navInfo.
 *   Identifier fields are SKIPPED — auto-generated by SequenceGenerator.
 *
 * ── Output side: transformEntityToJSON(dataObject, entity) ───────────────────
 *   Converts a DB row (column-keyed) into a JSON response object.
 *
 *   Ref entity fields (entity set, standaloneCRUD=false):
 *     DB returns:   STATUSID = 301
 *     API outputs:  {"status": {"id": 301, "name": "Open"}}
 *     → resolveRefEntityField() does a SELECT on the ref entity's table.
 *
 *   Sub-entity fields (standaloneCRUD=true) are SKIPPED — not in parent GET response.
 *   Internal fields (isInternal=true) are SKIPPED — never exposed in API responses.
 *
 * ── resolveRefEntityField(field, fkId) ───────────────────────────────────────
 *   Fetches {id, displayKey} from the ref entity's table.
 *   Uses getRaw() (bypasses range/tenant scoping — ref tables are global/shared).
 *   Returns {"id": fkId, [displayKey]: value} or {"id": fkId} on lookup failure.
 *   Returns null when fkId is null/undefined/0.
 */

const EntityTransformer = require('./EntityTransformer');
const dataAccess        = require('../Database/ORM/DataAccess');
const { SelectQueryImpl, Criteria, Column, Table } = require('../Database/QueryBuilder');

class JSONDOConverter extends EntityTransformer {

    constructor() {
        super();
    }

    // ── Input: JSON → DB columns ──────────────────────────────────────────────

    /**
     * Maps the client JSON payload to a plain column-keyed object suitable for
     * Row.set() calls. Called by PreDefaultEntityHandler.add() and .edit().
     *
     * @param {APIRequest} request
     * @returns {Promise<Object>} column-keyed plain object  e.g. { STATUSID: 301, SUBJECT: "..." }
     */
    async transformJSONToEntity(request) {
        const entity     = request.entity;
        const entityName = entity.getName();
        const fields     = entity.getFields();

        console.log(`[JSONDOConverter] transformJSONToEntity for entity: ${entityName}`);

        const rawInputData = request.inputData ? request.inputData.getEntityData() : {};
        if (!rawInputData) return {};

        // Input can be entity-keyed {"request": {...}} or flat {...}
        const entityData = rawInputData[entityName] || rawInputData;
        console.log('[JSONDOConverter] entityData ->', entityData);

        const dbObject = {};

        for (const field of Object.values(fields)) {
            // ── Skip: auto-generated PK — never written from client input ─────
            if (field.isIdentifier) continue;

            // ── Skip: sub-entity collection fields — they have own endpoints ──
            if (field.standaloneCRUD || field.isCollection) continue;

            // ── Skip: internal FK fields — injected by handler via navInfo ────
            // Internal fields are written explicitly in PreDefaultEntityHandler._injectParentFK()
            // after fillRefs() has put them into entityData; the handler reads them directly
            // from the Row constructed off the converter output. We include them here so
            // _injectParentFK can set them on the plainObj before building the Row.
            // However for PUT (edit), internal parent FK fields must never be overwritten.
            if (field.isInternal && request.operation === 'PUT') continue;

            // ── Skip: field not present in input ─────────────────────────────
            if (!Object.prototype.hasOwnProperty.call(entityData, field.name)) continue;

            const rawValue  = entityData[field.name];
            const colName   = field.getColumnName ? field.getColumnName() : (field.relationMapping ? field.relationMapping.split('.')[1] : field.name);

            // ── Ref entity field: unwrap {id: X} → write FK column only ──────
            if (field.refEntity && !field.standaloneCRUD) {
                let fkId = null;
                if (rawValue !== null && rawValue !== undefined) {
                    if (typeof rawValue === 'object') {
                        fkId = rawValue.id ?? null;
                    } else {
                        // Plain number/string ID supplied directly
                        fkId = rawValue;
                    }
                }
                dbObject[colName] = fkId;
                console.log(`[JSONDOConverter] ref field '${field.name}' → ${colName} = ${fkId}`);
                continue;
            }

            // ── Regular scalar field ─────────────────────────────────────────
            dbObject[colName] = rawValue;
        }

        console.log('[JSONDOConverter] Created dbObject ->', dbObject);
        return dbObject;
    }

    // ── Output: DB columns → JSON ─────────────────────────────────────────────

    /**
     * Converts a DB row (column-keyed plain object from Row.toObject()) into
     * an API JSON response object. Called by PreDefaultEntityHandler for all reads.
     *
     * Ref entity fields are expanded inline: {id: 301, name: "Open"}.
     * Sub-entity and internal fields are omitted from the response.
     *
     * @param {Object} dataObject   — plain column-keyed object from Row.toObject()
     * @param {Entity} entity       — entity definition
     * @returns {Promise<Object>}   — field-name-keyed JSON response
     */
    async transformEntityToJSON(dataObject, entity) {
        console.log(`[JSONDOConverter] transformEntityToJSON for entity: ${entity.getName()}`);

        const jsonResponse = {};
        const fields       = entity.getFields();

        for (const field of Object.values(fields)) {
            // ── Skip: sub-entity collection fields — not in parent GET response ─
            if (field.standaloneCRUD || field.isCollection) continue;

            // ── Skip: internal fields — FK fields, never exposed in API ────────
            if (field.isInternal) continue;

            const colName  = field.relationMapping ? field.relationMapping.split('.')[1] : field.name;
            const rawValue = dataObject[colName];

            // ── Ref entity field: expand FK id → nested object ─────────────────
            if (field.refEntity && !field.standaloneCRUD) {
                jsonResponse[field.name] = await this.resolveRefEntityField(field, rawValue);
                continue;
            }

            // ── Regular scalar field ──────────────────────────────────────────
            if (Object.prototype.hasOwnProperty.call(dataObject, colName)) {
                jsonResponse[field.name] = rawValue;
            }
        }

        return jsonResponse;
    }

    // ── Ref entity resolution ─────────────────────────────────────────────────

    /**
     * Fetches the display object for a ref entity field.
     *
     * Returns { id: fkId, [displayKey]: value } — only the PK + display_key field.
     * This matches SDP's getPartialData() behaviour (partial_field pattern):
     * only {id, display_key_field} are returned, not all fields.
     *
     * Uses getRaw() (bypasses tenant range scoping) because ref entities like
     * "status", "priority", "category" are global or shared across tenants.
     *
     * Graceful degradation:
     *   - fkId is null/undefined/0  → returns null
     *   - ref entity not registered  → returns {id: fkId} with a warning
     *   - ref record not found       → returns {id: fkId} (record may have been deleted)
     *   - displayKey field not found → returns {id: fkId}
     *
     * @param {EntityField} field   — the ref field definition (has .refEntity, .displayKey)
     * @param {number|null} fkId    — the raw FK id from the DB column
     * @returns {Promise<Object|null>}
     */
    async resolveRefEntityField(field, fkId) {
        // Null / sentinel check
        if (fkId === null || fkId === undefined || fkId === 0 || fkId === '') {
            return null;
        }

        // Look up the ref entity definition
        const Entity    = require('../API/Entity');
        const refEntity = Entity.getEntityByName(field.refEntity);

        if (!refEntity) {
            console.warn(
                `[JSONDOConverter] resolveRefEntityField: entity '${field.refEntity}' not registered — ` +
                `returning {id: ${fkId}} for field '${field.name}'`
            );
            return { id: fkId };
        }

        const refTable   = refEntity.getTableName();
        const refPkField = refEntity.getIdentifierField();

        if (!refTable || !refPkField) {
            console.warn(
                `[JSONDOConverter] resolveRefEntityField: cannot determine table/PK for '${field.refEntity}'`
            );
            return { id: fkId };
        }

        const refPkCol     = refPkField.getColumnName();
        const displayKey   = field.displayKey;   // e.g. "name"

        // Build a minimal SELECT: just PK + display_key column
        const sq = new SelectQueryImpl(Table.getTable(refTable));
        sq.setCriteria(Criteria.eq(Column.getColumn(refTable, refPkCol), fkId));

        // Determine the display_key column name from the ref entity's field definition
        let displayColName = null;
        if (displayKey) {
            const displayField = refEntity.getFieldByName(displayKey);
            if (displayField) {
                displayColName = displayField.getColumnName ? displayField.getColumnName() : displayKey;
            }
        }

        let rows;
        try {
            // getRaw() bypasses tenant range scoping — correct for shared ref tables
            rows = await dataAccess.getRaw(sq);
        } catch (err) {
            console.warn(
                `[JSONDOConverter] resolveRefEntityField: DB error for '${field.refEntity}#${fkId}': ${err.message}`
            );
            return { id: fkId };
        }

        if (!rows || rows.length === 0) {
            console.warn(
                `[JSONDOConverter] resolveRefEntityField: '${field.refEntity}#${fkId}' not found in DB — ` +
                `record may have been deleted`
            );
            return { id: fkId };
        }

        // rows[0] is a Row instance — use toObject() to get the plain column-keyed map
        const rawRow    = rows[0].toObject ? rows[0].toObject() : rows[0];
        const resolvedId = rawRow[refPkCol] ?? fkId;
        const result     = { id: resolvedId };

        if (displayColName && Object.prototype.hasOwnProperty.call(rawRow, displayColName)) {
            result[displayKey] = rawRow[displayColName];
        }

        console.log(
            `[JSONDOConverter] resolveRefEntityField: '${field.name}' → `,
            result
        );

        return result;
    }
}

// Export as a reusable singleton
module.exports = new JSONDOConverter();
